---
title: "Parameterized Report (demo)"
author: "Jane Smith (Jacobs)"
date: "`r Sys.Date()`"
params:
  file_plots: NULL
output:
  officedown::rdocx_document:
    base_format: "bookdown::word_document2"
    reference_docx: !expr here::here('StyleTemplates', 'WordStyleTemplates', 'WordTemplate.docx')
    reference_num: FALSE
    number_sections: FALSE
bibliography: "`r here::here('References', 'TestReferences.bib')`"
link-citations: yes
csl: "`r here::here('References', 'ReferenceStyles', 'chicago-author-date.csl')`"
---

```{r setup, include = FALSE}
# Set knitr options.
knitr::opts_chunk$set(echo = FALSE,
                      warnings = FALSE,
                      fig.align = "center",
                      fig.width = 6, fig.height = 4)

# Load packages.
## The following only loads packages that are required for this template.
if (!require("pacman")) install.packages("pacman") # p_load from the pacman package checks if packages are installed, installs them if not, then loads them.
pacman::p_load(devtools, BiocManager, # packages for loading/installing other packages
               here, # for using project-relative paths
               cowplot, gridGraphics, # for plotting
               flextable, # for tables
               knitr, bookdown, # for additional knitting options
               officedown, officer, mschart, # for producing Office documents and charts
               tidyverse) # for general data manipulation and piping

# Set other options.
## This ensures that Office charts produced by the mschart package match the width and height of the figures in the .docx report.
formals(ph_location)[c("width", "height")] <- knitr::opts_chunk$get()[c("fig.width", "fig.height")]

report_plots <- readRDS(here::here(params$file_plots))
```

This report received `r length(params$report_plots)` plots from Shiny.

The names of the plots are: `r names(params$report_plots)`

What do the plot objects look like?

```{r}
print(report_plots)
```

## Plot 1

```{r}
report_plots[["Plot1"]]
```

## Other plots

```{r}
report_plots[!(names(report_plots) %in% "Plot1")]
```

This was made in R [@R-base].

<div id="refs"></div>
