---
title: "Test App"
author: "John Smith (Jacobs)"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
# Clean the global environment.
rm(list = ls())

# Set knitr options.
knitr::opts_chunk$set(echo = FALSE,
                      fig.align = "center",
                      fig.width = 6, fig.height = 4)

# Load packages.
## The following only loads packages that are required for this template.
# p_load from the pacman package checks if packages are installed, installs them if not, then loads them.
if (!require("pacman")) install.packages("pacman")

pacman::p_load(devtools, BiocManager, # packages for loading/installing other packages
               here, # using project-relative paths
               openxlsx, readxl, # reading in data
               lubridate, # date-times
               EnvStats, # toxicological functions 
               cowplot, gridGraphics, # for plotting
               flextable, # for tables
               knitr, bookdown, # for additional knitting options
               officedown, officer, mschart, rvg, # for producing Office documents and charts
               shiny, shinyWidgets, shinydashboard, # Shiny packages
               rmarkdown, knitr, tinytex, # Markdown and related
               tidyverse) # for general data manipulation and piping
```

# Introduction

# Demonstration

```{r, echo = FALSE, out.height= 20}
shinyApp(
  
  ui <- fluidPage(
    sliderInput("slider", "Slider", 1, 100, 50),
    downloadButton("report", "Generate report"),
    ),

    server = function(input, output) {
      
    output$report <- downloadHandler(
      # For PDF output, change this to "report.pdf"
      
      filename = "report.html",
      
      content = function(file) {
        
        # Copy the report file to a temporary directory before processing it, in
        # case we don't have write permissions to the current working dir (which
        # can happen when deployed).
        tempReport <- file.path(tempdir(), "report.Rmd")
        # tempReport <- file.path(tempdir(), here::here("ShinyMarkdownReports/Reports/Report.Rmd"))
        file.copy(here::here(
          "ShinyMarkdownReports", "Apps", "reports", "report.Rmd"),
          tempReport, overwrite = TRUE)
        # file.copy(here::here("ShinyMarkdownReports/Reports/Report.Rmd",
                             # tempReport, overwrite = TRUE))

        # Set up parameters to pass to Rmd document
        params <- list(n = input$slider)

        # Knit the document, passing in the `params` list, and eval it in a
        # child of the global environment (this isolates the code in the document
        # from the code in this app).
        rmarkdown::render(tempReport, output_file = file,
          params = params,
          envir = new.env(parent = globalenv())
        )
      }
    )
    }
)
```